@startuml
entity dto.ModuleInfo.Details {
  +name: String
  +description: String
  +main_window: QWidget

  {static}from_module(module: types.ModuleType): dto.ModuleInfo.Details
}
dto.ModuleInfo.Details --> QWidget

entity dto.Calculation.Result {
    +value: Float | Int
}
dto.Calculation.Result --> dto.ModuleInfo.Details
note bottom of dto.Calculation.Result
    The Result of a Calculation can be either of type Float or Int
end note

entity dto.Calculation.Input {
    +input: List[Float|Int|String]
}

interface Module {
    +input(List[Float])
    +calculate(input: List[Float]): dto.Calculation.Result
}

class ModulesWidget {
    -available_modules: List<dto.ModuleInfo>
    -modules_base_path: pathlib.Path
    -active_module: ModuleInfo.Details

    -load_module(module_name: String)
    -get_available_modules(): List<dto.ModuleInfo>
}
ModulesWidget <|-- QWidget
ModulesWidget --> dto.ModuleInfo.Details
note bottom of ModulesWidget
    Widget to display the active Module and offer a way to
    switch between different Modules
end note


MainWindow <|-- QWidget
MainWindow --* ModulesWidget

@enduml